### ISSUE TITLE
quelques soucis après installation

### ISSUE THREAD

**Issue by faman74** [Patrick-81/NAFABox#10]
Bonjour et merci pour le support boulot !

Après avoir installé Nafabox sur une tinkerboard, j'ai rencontré quelques soucis :

- au démarrage, un message d'erreur m'indique qu'il manque un dossier home/mon_nom/downloads. J'ai suivi un tuto ubuntu pour corriger cela, mais rien n'y fait.

- au démarrage, de manière aléatoire, les icônes d'applications sont absentes du bureau. Si je vais dans le dossier "bureau", je les trouve mais elles n'apparaissent pas sur le bureau... après quelques  manipulations elles réapparaissent. Je n'ai pas encore bien compris ni pourquoi ni comment...

- au démarrage, l'affichage de l'arrière plan par défaut est "mosaïque", ce qui est très moche, j'ai beau le changer (étirer), à chaque redémarrage, il revient à mosaïque.

- impossible de se connecter avec un autre appareil au hotspot quand il est crée par la procédure indiquée ici http://nafabox.linux-astro.fr/#reseau 
L'appareil reste en attente d'une adresse IP et fini par buguer
Par contre, ça fonctionne bien avec la procédure https://github.com/Patrick-81/NAFABox/blob/master/ConfigTinker/Install_Hotspot_Armbian.md mais le hotspot n’apparaît pas dans les réseaux wifi utilisés par la Tinkerboard.

J'ai configuré la tinkerboard en me connectant sur une télé en hdmi, A chaque reboot, l'écran de la télé clignote et ne revient jamais sur le bureau, il me faut changer de canal hdmi puis revenir sur celui de la tinkerboard pour enfin avoir le bureau s'afficher normalement (c'est peut être plus un souci du à la télé ?).

Enfin, je ne trouve plus la procédure pour passer le clavier en azerty ni celle pour modifier la partition et qui sont je crois à faire dès le début ?

Voilà, c'est à peu près tout pour le moment. Merci beaucoup 👍

**Comment by dragonlost** [comment]
hello !

- l'histoire du dossier qui manque c'est du à blueman (gestionaire de bluetooth) qui trouve plus ton dossier télechargement car il a changé de nom quand tu as fait le changement en langue en  francais ( download -> télechargement). 

Pour résoudre ca tu tape dans un terminal : 
`gsettings set org.blueman.transfer shared-path '/home/toto'`

en remplacant **"toto"** par le nom que tu as choisi. Attention de ne pas oublier les guillemet qui sont important

- pour les icones du bureau c'est du au changement de nom du dossier bureau ( desktop -> bureau) qui se passe mal. en théorie il devrai d'abord transferer les icone avant de change de langue mais il le fait pas ( bug de armbian). 

pour resoudre : normalement dans **/home/toto** tu as un dossier **Desktop** et **Bureau**. Tu transfert tout dans le dossier **Bureau** et tu supprime le dossier **Desktop**. Tu redémare.

Si après changement tu toujour un problème il faut que t'aille changer à la main l'adresse du dossier "Bureau", pour ca : 
Vas dans **/home/toto**, fait **CTR+h** (pour faire apparaitre les fichier/dossier caché, c'est ceux qui commence par un **.**) vas dans le dossier **.config** puis tu ouvre le fichier **user-dirs.dirs** tu change la bonne ligne, tu enregistre et c'est bon !

- Alors la c'est un bug de la Tinkerboard qui a un port HDMI super capricieux. Selon les écran et la resolution demander ca peut arriver de ce retrouver avec une image mosaique ou juste un boux d'image. Quand ca t'arrive soit tu change de resolution soit tu ouvre l'application **Setres** et tu choisi ta resolution. ca devrai réglé le problème.

- pour le hotspot et pour toute la doc en général, le github a resont ! donc il faut suivre la doc du github pour le hotspot. Quand tu crer le hotspot c'est norale que tu ne voit plus ta connexion wifi car c'est un autre logiciel qui a pris la mains dessus ( hostapd). si tu le desactive tu récupérera ta connection wifi.

- Oui les Télé/écran et les micro ordinateur c'est pas une histoire d'amour ! Armbian qu'on utilise n'a pas les même moyen que raspbian pour ce développer ca qui implique plus de bug potentiel et plus de temps pour les resoudres. Mais c'est un super système quand même pour la tinkerboard et autre carte ( sauf pour le rpi).

- Pour la partition je pense que tu parle de la tailleµ. si tu as installer via les script elle doit déjà être a la bonne taille. Si tu es passer par les images toutes faites il faut effectivement l'expandre afin d'utiliser toute la place : https://www.youtube.com/watch?v=R-NZFkVL0B4

- pour le clavier, normalement il aurait tu te le proposer au début de l'installation :  sinon tu vas dans le **Menu** puis **Education** et la tu lance **Reconfig_keyboard**

Je pense que j'ai rien oublié.

**Comment by faman74** [comment]
Nickel, merci beaucoup pour la réponse ultra détaillée. Je vais tester tout
ça !
Je reviendrai avec d'autres questions plutôt orienté utilisation ensuite.
Je suppose que ça aura plus sa place sur le forum que sur le github.

Merci beaucoup d'avoir pris le temps de me répond et a+

Le mer. 4 sept. 2019 à 18:29, dragonlost <notifications@github.com> a
écrit :

**Comment by dragonlost** [comment]
N'hésite pas a pauser tes questions ici aussi.
