### ISSUE TITLE
Problème avec la caméra Pi V2.1

### ISSUE THREAD

**Issue by domdomz** [Patrick-81/NAFABox#11]
Bonjour et bravo pour votre super boulot.
Je viens d'installer ma NAFABox sur un Asus Tinker et après avoir branché ma caméra elle ne semble pas être détectée.
Comment tester ? J'ai essayé avec V4Utils et media-ctl mais rien n'apparait en entité 7...
Pour info je viens de tester avec l'image 20190821-tinker-board-linaro-stretch-alip-v2.0.11.img et la caméra est détectée...
Merci d'avance
Dominique

**Comment by dragonlost** [comment]
Bonjour et merci.

Hello. Alors, a ce que j'en est vue et compris sur le forum armbian. Les camera RPI ne sont pas compatible car les drivers pour la tinkerboard ne sont pas open source.

TinkerOS n'intégre pas que des driver open source contrairement à Armbian.

Apres concretement, la camera du raspberry n'est pas du tout adapté pour l'astronomie. Mais je trouve aussi que c'est dommage qu'elle ne fonctionne pas.

Le plus simple serait de posé directment la question au personne qui gére Armbian : 
Ouvrez un poste ici : https://forum.armbian.com/forum/21-rockchip-3288-3328/
avec le maximum de description.

Par contre le poste doit être en anglais.
Malheurement les script ne sont pas compatible débian et donc il ne devrai pas marcher sur tinkerOS.

**Comment by domdomz** [comment]
Bonjour et merci pour la réponse rapide, même si elle me déçoit un peu … Ah les joies de linux, de l’open source, de la doc et des distributions tous azimuts.
Je suis un informaticien à la retraite qui vient plutôt du monde Microsoft et j’ai souvenir que sur nos serveurs Unix/Linux nos collègues avaient les mêmes problèmes ;-(((
Quant à l’inaptitude de la caméra pour l’astronomie, ce n’est pas ce que j’avais cru comprendre, voir  : https://www.framboise314.fr/astrophotographie-avec-le-raspberry-pi/ ou https://www.minimachines.net/actu/astronomes-allez-adorer-camera-raspberry-pi-19491
Je vais essayer d’avancer de mon côté sinon je continuerai d’utiliser mon Olympus qui fait déjà bien l’affaire ;-)
Encore merci pour la réponse
Dominique
PS: je vais faire le post sur armbian on ne sait jamais (l’anglais n’est pas un gros problème pour moi)
