### ISSUE TITLE
Question OS pour NAFABox

### ISSUE THREAD

**Issue by HamHamFonFon** [Patrick-81/NAFABox#12]
Bonjour, préférant utiliser Debian que Ubuntu sur mon RPi, est-ce que la NAFABox est bien compatible avec Rasbian ? Ou alors il vaut vraiment mieux être sur Ubuntu Mate ?
Merci d'avance :)

**Comment by dragonlost** [comment]
Bonjour.

En soit, il n'y a pas de point bloquant mais il faut pas mal adaptée les scripts poura être compatible avec raspbian.

Pour l'instant les scripts sont compatibles uniquement avec Ubuntu (mate, xubuntu, kubuntu, lubuntu

**Comment by HamHamFonFon** [comment]
Merci beaucoup pour votre réponse rapide. J ai néanmoins fais le test et l'installation des composants Mate a fait beaucoup de bazar et je n'avais plus d'interface graphique, car le script a planté au lancement de update_conf.sh (ligne 120) : il semblerai qu'il ne trouvait pas le path du script.
L'issue peut être fermée :)
