### ISSUE TITLE
Problème de distribution

### ISSUE THREAD

**Issue by peebee** [Patrick-81/NAFABox#14]
Je n'arrive pas à comprendre pourquoi il veut installer la version Focus alors que 
le fichier lsb_release pointe sur bionic 
tous les fichier sources sont par défaut en focus ? 
Je ne sais pas si cela vient de votre code source, a priori non mais d'ou cela peut venir ?

**Comment by dragonlost** [comment]
hello. c'est sur quel carte ?

**Comment by dragonlost** [comment]
pour info sur armbian y a un bug actuellement qui fait que tout les ppa ajouter pointe sur focal (20.04). le bug a était corriger mais tout les image > 5.90 sont bugé. faut attendre les nouvelle image. d'ou la precision de la version dans les tuto.

**Comment by peebee** [comment]
Je suis sur un Tinker Board en 5.90, le bug doit exister sur cette version aussi 
J'ai fini l'installation à la main 
je suis en Next 5.95, installé de ce matin, je passe en 5.90 et la 5.95 vient d'être supprimé du repo

**Comment by dragonlost** [comment]
avez vous freezer le firmware avant d'installer quoi que ce soit ? si vous avez fait un update/upgrade et que vous n'avez pas freezer le firmware avant alors la mise a jour du firmware a introduit le bug.

**Comment by peebee** [comment]
IL est bien Freezé

**Comment by peebee** [comment]
Je viens de repartir sur un nouvelle sd card 
Installation de la version Armbian_19.11.3.346_Tinkerboard_bionic_legacy_4.4.199_desktop

- init sans aucune mise à jour 
- armbian-config 
- passage en 5.85 (Next) j'ai pas plus ancien 
- reboot 
- armbian-config 
- freeze version 

Test avec la commande 
- sudo apt-add-repository ppa:mutlaqja/ppa

Controle dans /etc/apt/sources.list.d/mut*
les paquets sont bien en Focal et non en bionic, visiblement les version 5.85 + sont buggé, y a t il une solution autre que d'ajouter les repo à la main ?

**Comment by peebee** [comment]
Effectivement cela a été corrigé dans le pull https://github.com/armbian/build/pull/1677
Mais il n'existe encore aucune image compilé 

Je viens de trouvé dans les archive un 5.77 d'avril qui est fonctionnelle, et je viens de "freeze" le kernel

**Comment by peebee** [comment]
Je clos l'incident

**Comment by peebee** [comment]
Bonjour @dragonlost,

Je viens de tester la version d'hier le problème avec le PPA est corrigé, du moins sur la https://dl.armbian.com/tinkerboard/Bionic_current_desktop

**Comment by dragonlost** [comment]
Bonjour.
Je vais tester les nouvelles version du 27/12 et 11/01 pour voir si le bug PPA est résolue dedans.
Une fois fait je mettrai a jour la version recommandé pour une nafabox.

Attention : sur la nafabox on utilise plutot la version "stable" car elle est plus stable que la version "current"
