### ISSUE TITLE
Problème avec camera ZWO 533

### ISSUE THREAD

**Issue by mg95-16** [Patrick-81/NAFABox#16]
C'est avec beaucoup d'impatience et de gratitude que j'ai installé l'image NAFABox_Desktop_Tinkerboard_3.3.1.zip
J'ai créé un profil pour une ZWO CCD ASI533MC Pro.
Ce profil démarre bien mais quand on veut prendre une photo on obtient :
"Job requires 1,000-second  images, has 0/1 frames captured and will be processed."
"Capturing 1,000-second  image..."
ZWO CCD ASI533MC Pro :  "[ERROR] Exposure failed after 3 attempts. "
"Capture failed. Check INDI Control Panel for details."
"Restarting capture attempt #1"
"Capturing 1,000-second  image..."
EKOS se met en boucle et je dois arrêter le profil.

Pour sortir du contexte NafaBox j'ai installé Kstars sur une VM Ubuntu 18.04.2 LTS Noyau Linux 4.18.0-15-generic x86_64 Mate 1.20.1 avec les instructions suivantes 👍 
sudo apt-add-repository ppa:mutlaqja/ppa
sudo apt-get update
sudo apt-get install indi-full kstars-bleeding

Et là ça fonctionne.

J'ai fais les mêmes mises à jour sur la Tinkerboard mais j'ai toujours le problème.

Ne pourrait il pas y avoir un problème de droits d'écriture quand on récupère la photo ?

Ci joint les logs mais je trouve quelles ne sont pas très détaillées, je les ai pourtant configurées avec le niveau verbose.
[log_07-30-39.txt](https://github.com/Patrick-81/NAFABox/files/4033923/log_07-30-39.txt)
[nafabox.log](https://github.com/Patrick-81/NAFABox/files/4033924/nafabox.log)

C'est dommage parce-que le reste fonctionne parfaitement et le concept de NafaBox correspond exactement à des besoins d'astrophoto nomade.

**Comment by dragonlost** [comment]
Bonjour.

Désolé de ne vous répondre que maintenant. Mais malheureusement cela à l'air d'être un problème avec le driver ASI. Ca marche sur votre VM car c'est le driver amd64 qui est utiliser ( en général il est plus stable) au lieu du driver arm32 comme sur votre tinkerboard.

Je vous invite à lancer la commande suivante pour mettre à jour le driver indi :
sudo apt install indi-full

**Comment by mg95-16** [comment]
J'ai laissé tombé la Tinker Board.
Une fois que l'on a gouté à l'USB 3 ;-)
