### ISSUE TITLE
fautes d'orthographe

### ISSUE THREAD

**Issue by lionel13** [Patrick-81/NAFABox#17]
Bonjour,

Bravo pour votre énorme travail. Je débute en astrophotographie et sur les conseils d'un ami de mon club d'astro j'ai installé NAFABox sur un PC portable avec xubuntu.
Je découvre petit à petit les différents logiciels.

En cliquant sur l'icône du bureau "Update_nafabox_script", une popup s'ouvre demandant si on souhaite mettre à jour les scripts.
Dans cette popup il y a des fautes d'orthographe : mettere au lieu de mettre et script au singulier

https://github.com/Patrick-81/NAFABox/blob/a991c3850f9dc4574a1c56a5d6c142b9b171e3d3/ConfigTinker/update_nafabox_script.sh#L25

Bonne continuation

**Comment by dragonlost** [comment]
merci je vais corriger

**Comment by dragonlost** [comment]
voilà c'est fait !
