### ISSUE TITLE
Pb Wifi avec Raspberry 4B

### ISSUE THREAD

**Issue by mg95-16** [Patrick-81/NAFABox#18]
Installation faite à partir de NAFABox_Desktop_RPI_3.3.1
Le RP4B voit bien les réseaux wifi.
Il peut se connecter et reçoit bien une adresse IP et la configuration associée.
Mais à partir du RP4B je ne peux pas pinguer la passerelle.
D'un autre PC sur le même réseau, on ne peut pas pinguer le RPB4.

**Comment by mg95-16** [comment]
Si l'on fait l'installation à partir de 2019-09-26-raspbian-buster-full puis des dépôts Indi, le problème disparait.

**Comment by dragonlost** [comment]
quand vous dit l'installation, vous parlez de quoi ?

**Comment by dragonlost** [comment]
> 
> 
> Si l'on fait l'installation à partir de 2019-09-26-raspbian-buster-full puis des dépôts Indi, le problème disparait.

les script nafabox ne sont pas adapter à raspbian/debian (apt-add-repository marche pas dans debian)

**Comment by mg95-16** [comment]
Je flashe la carte SD avec https://downloads.raspberrypi.org/raspbian_full_latest.
J'installe Kstar Ekos Indi à partir de https://www.indilib.org/download/raspberry-pi.html
Désolé pour votre travail mais je n'utilise plus les scripts ni les images NafaBox.
Je suis parti de ce que "préconisait" le constructeur et le développeur.

**Comment by dragonlost** [comment]
Pour  NAFABox_Desktop_RPI_3.3.1, vous pouvez lancer le script de mise à jour du firmware qui est présent dans le dossier /home/ --> Updater.sh qui vas mettre à jour votre raspberry.

J'ai eu des retour positif sur cette mise a jour.
Je pense sortir une 3.3.2 dans le mois avec la version 3.3.9 de kstars et ASTAP en plus.

**Comment by peebee** [comment]
la dernière version server 18.04.4 prend en compte le RPI4 maintenant 
https://ubuntu.com/download/raspberry-pi/thank-you?version=18.04.4&architecture=arm64+raspi3

**Comment by peebee** [comment]
Très instable avec la version ARM64 (Kstart plante souvent) , je test la version ARMHF

**Comment by dragonlost** [comment]
a super. Hésité pas à me tenir au courant de vos différents tests.

**Comment by dragonlost** [comment]
N'hésitez pas a utiliser la version toute faite pour RPI3/4 que j'ai mis a disposition aussi.
Si vous avait un bug/instabilité, n'hésitez pas a mettre a jour a l'aide de la commande : `sudo /home/Updater.sh`

**Comment by peebee** [comment]
Je pense que je vais la tester, car je rencontre des problèmes avec les versions officielles et les drivers de ASI

**Comment by dragonlost** [comment]
https://github.com/Patrick-81/NAFABox/blob/master/doc/BUG_and_DEBUG_list.md

J'ai écrit un tuto pour éviter le bug du wifi qui est du au mode eco qui s'active.
